services:
  redis:
    image: redis:7-alpine
    container_name: wsaksham_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass yourpassword

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wsaksham_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo:7
    container_name: wsaksham_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"